const content = [
	{
		id: 1,
		tech: 'React-Native',
		tech2: '../../assets/logo-logomark.png',
		image: require('../../assets/Market/M2.png'),
		title: 'Saturday Market',
		text:
			'Mobile application built with React-Native and firebase. This is a social application and virtual market place for selling handcrafted goods and art. This application is built to be multi-platform, including ios, android and web. User authentication and stored images and posts are enabled with Firebase/Firestore.',
		projectLink: 'https://expo.io/@angelena/projects/saturdaymarket',
		projectLinkName: '/expo-app-1',
		link: 'https://github.com/chelsea-angelena/Expo-SaturdayMarket',
		linkName: '/SaturdayMarket',
		loomDemoLink: '',
		loomDemoLinkName: '/LoomMarketDemo',
		demolink: '/MarketDemo',
		demolinkName: '/MarketDemo',
		sim: 'market',
		button: 'market',
		pubKey: '',
	},
	{
		id: 2,
		tech: 'React-Native',
		tech2: 'Movie App',
		image: require('../../assets/OMDB/sim1.png'),
		title: 'The Movie App',
		text:
			'A movie search app. Search for your favorite movies and save the list to reference later. This app uses React-Native and Expo for the client side, as well as the Firebase SDK for user Authentication and Firestore as the database. There is also has a Node.js/Express.js server for interacting with the Open-Movie-DataBase.',
		projectLink: 'https://expo.io/@angelena/projects/movie-search-app',
		projectLinkName: '/expo-movie-app',
		link: 'https://github.com/chelsea-angelena/expo-movie-app',
		linkName: '/react-native-omdb',
		loomDemoLink: 'https://www.loom.com/share/21ca1ce9b0a746f2925a7136d1fc37a9',
		loomDemoLinkName: '/LoomMovieDemo',
		demolink: '/movieAppDemo',
		demolinkName: '/Movie',
		sim: 'movie',
		button: 'movie',
		pubKey: 'h96ch5mct9gc05ze9fkg2g6rfg',
	},
	{
		id: 3,
		tech: 'React-Native',
		tech2: 'Yelp API',
		image: require('../../assets/simulator_screenshot_8F1DD085-E204-4365-BFF9-DA0977CFD595.png'),
		title: 'Good Eats',
		text:
			'Mobile App, built with React-Native. Search for  nearby restaurants by the type of cuisine, or business name. The app will automatically use location, only after explicit permission has been granted by the user, so all search results are local. Find the hours, location, ratings and price range of restuarants near you.',
		projectLink: 'https://expo.io/@angelena/projects/restaurantsearch',
		projectLinkName: '/expo-app-2',
		link: 'https://github.com/chelsea-angelena/restaurant-app',
		linkName: '/goodEats',
		loomDemoLink: '',
		loomDemoLinkName: '/LoomYelpDemo',
		demolink: 'https://chelsea-angelena.github.io',
		demolinkName: '/demo3',
		sim: 'yelp',
		button: 'yelp',
		pubKey: '',
	},
];
export default content;
